_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
            "3":
                - 1
                - 2
                - 13
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.6
            "6": 4.47.1
            "8":
                - 1
                - 5
            "12": 0.19.6
            "13": linux-x86_64
