repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 6.0.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.1  
    hooks:
      - id: commitizen
        stages: [commit-msg]
        type: commit-msg